// ============================================================
// CONSTANTS - সকল স্থির ডেটা এখানে সংজ্ঞায়িত করা হয়েছে
// ============================================================

import type { Subject, Homework, Suggestion, Announcement, ChatMessage } from "@/types";

// Admin Credentials (Production এ Supabase Auth ব্যবহার করতে হবে)
export const ADMIN_CREDENTIALS = {
  email: "admin@madrasa.edu",
  password: "madrasa@2025",
};

export const MADRASA_INFO = {
  name: "গাজীর চট মদিনাতুল উলুম ফাজিল মাদরাসা",
  class: "দাখিল ৮ম শ্রেণী",
  session: "২০২৫-২০২৬",
  address: "গাজীর চট, চট্টগ্রাম, বাংলাদেশ",
  phone: "০১৮০০-০০০০০০",
  ebtedayee: "EBTEDAYEE - ৮",
};

// দাখিল ৮ম শ্রেণীর সব বিষয়
export const DEFAULT_SUBJECTS: Subject[] = [
  {
    id: "1",
    name: "আল-কুরআন ও তাজবিদ",
    nameEn: "Al-Quran & Tajweed",
    teacher: "মাওলানা আব্দুর রহমান",
    teacherDesignation: "সিনিয়র শিক্ষক",
    icon: "📖",
    color: "#c9a227",
    description: "কুরআন তিলাওয়াত, হিফজ ও তাজবিদের নিয়ম-কানুন শেখানো হয়।",
    totalClasses: 120,
    completedClasses: 78,
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "আল-আকাইদ ওয়াল ফিকহ",
    nameEn: "Aqeedah & Fiqh",
    teacher: "মাওলানা মুহাম্মদ ইউসুফ",
    teacherDesignation: "প্রধান শিক্ষক",
    icon: "🌙",
    color: "#2d9d64",
    description: "ইসলামের মূল বিশ্বাস ও আইন-কানুন সম্পর্কে বিস্তারিত আলোচনা।",
    totalClasses: 100,
    completedClasses: 65,
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "আল-হাদিস ও উসুলুল হাদিস",
    nameEn: "Hadith & Usoolul Hadith",
    teacher: "মাওলানা হাফিজুর রহমান",
    teacherDesignation: "সহকারী শিক্ষক",
    icon: "📜",
    color: "#c9a227",
    description: "হাদিসের জ্ঞান ও হাদিস বিজ্ঞানের মূলনীতি শেখানো হয়।",
    totalClasses: 90,
    completedClasses: 55,
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "বাংলা",
    nameEn: "Bangla",
    teacher: "জনাব মোহাম্মদ আলী",
    teacherDesignation: "বিষয় শিক্ষক",
    icon: "অ",
    color: "#1a6b3c",
    description: "বাংলা ভাষা ও সাহিত্য - গদ্য, পদ্য, ব্যাকরণ ও রচনা।",
    totalClasses: 120,
    completedClasses: 82,
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "ইংরেজি",
    nameEn: "English",
    teacher: "জনাব রফিকুল ইসলাম",
    teacherDesignation: "ইংরেজি শিক্ষক",
    icon: "A",
    color: "#c9a227",
    description: "English Grammar, Composition, Reading & Writing skills.",
    totalClasses: 120,
    completedClasses: 70,
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "গণিত",
    nameEn: "Mathematics",
    teacher: "জনাব কামাল উদ্দীন",
    teacherDesignation: "গণিত শিক্ষক",
    icon: "∑",
    color: "#2d9d64",
    description: "বীজগণিত, জ্যামিতি, পাটিগণিত ও ত্রিকোণমিতি।",
    totalClasses: 150,
    completedClasses: 95,
    createdAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "বিজ্ঞান",
    nameEn: "Science",
    teacher: "জনাব নাসির উদ্দীন",
    teacherDesignation: "বিজ্ঞান শিক্ষক",
    icon: "⚗️",
    color: "#1a6b3c",
    description: "সাধারণ বিজ্ঞান - পদার্থ, রসায়ন ও জীববিজ্ঞানের পরিচিতি।",
    totalClasses: 100,
    completedClasses: 60,
    createdAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "বাংলাদেশ ও বিশ্বপরিচয়",
    nameEn: "Bangladesh & World",
    teacher: "জনাব আমিনুল ইসলাম",
    teacherDesignation: "সমাজবিজ্ঞান শিক্ষক",
    icon: "🌍",
    color: "#c9a227",
    description: "বাংলাদেশের ইতিহাস, ভূগোল ও বিশ্বের সাথে সম্পর্ক।",
    totalClasses: 80,
    completedClasses: 50,
    createdAt: new Date().toISOString(),
  },
  {
    id: "9",
    name: "আরবি সাহিত্য ও ব্যাকরণ",
    nameEn: "Arabic Literature & Grammar",
    teacher: "মাওলানা ইবরাহীম খলিল",
    teacherDesignation: "আরবি বিভাগ প্রধান",
    icon: "ع",
    color: "#2d9d64",
    description: "আরবি ভাষার ব্যাকরণ (নাহু-সরফ) ও সাহিত্য চর্চা।",
    totalClasses: 120,
    completedClasses: 80,
    createdAt: new Date().toISOString(),
  },
  {
    id: "10",
    name: "তথ্য ও যোগাযোগ প্রযুক্তি",
    nameEn: "ICT",
    teacher: "জনাব সাইফুল ইসলাম",
    teacherDesignation: "আইসিটি শিক্ষক",
    icon: "💻",
    color: "#1a6b3c",
    description: "কম্পিউটার বেসিক, ইন্টারনেট ব্যবহার ও ডিজিটাল দক্ষতা।",
    totalClasses: 80,
    completedClasses: 45,
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_HOMEWORK: Homework[] = [
  {
    id: "h1",
    subjectId: "1",
    subjectName: "আল-কুরআন ও তাজবিদ",
    title: "সূরা ইয়াসিন মুখস্থ করা",
    description: "সূরা ইয়াসিনের প্রথম ১০ আয়াত মুখস্থ করে আনতে হবে এবং তাজবিদ সহ পড়তে হবে।",
    dueDate: "২০২৪-০১-২০",
    isUrgent: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "h2",
    subjectId: "6",
    subjectName: "গণিত",
    title: "অনুশীলনী ৫.২ সমাধান",
    description: "বইয়ের ৮৭-৮৯ পৃষ্ঠার অনুশীলনী ৫.২ এর সকল অঙ্ক খাতায় করে আনতে হবে।",
    dueDate: "২০২৪-০১-১৮",
    isUrgent: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "h3",
    subjectId: "4",
    subjectName: "বাংলা",
    title: "রচনা লেখা - আমার স্বপ্নের বাংলাদেশ",
    description: "'আমার স্বপ্নের বাংলাদেশ' শিরোনামে ৩০০ শব্দের একটি রচনা লিখে আনতে হবে।",
    dueDate: "২০২৪-০১-২২",
    isUrgent: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "h4",
    subjectId: "5",
    subjectName: "ইংরেজি",
    title: "Write a paragraph - My School",
    description: "Write a paragraph about 'My School' in 150 words. Use present tense and descriptive language.",
    dueDate: "২০২৪-০১-১৯",
    isUrgent: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "h5",
    subjectId: "9",
    subjectName: "আরবি সাহিত্য ও ব্যাকরণ",
    title: "নাহুর ব্যাকরণ অনুশীলন",
    description: "ইসমের প্রকারভেদ এবং ফেলের বিভক্তি সংক্রান্ত ১০টি বাক্য তৈরি করে আনতে হবে।",
    dueDate: "২০২৪-০১-২১",
    isUrgent: false,
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_SUGGESTIONS: Suggestion[] = [
  {
    id: "s1",
    subjectId: "6",
    subjectName: "গণিত",
    title: "অর্ধবার্ষিক পরীক্ষার সাজেশন",
    description: "এই সাজেশন অনুযায়ী ভালোভাবে পড়লে ভালো রেজাল্ট পাওয়া সম্ভব।",
    examType: "অর্ধবার্ষিক",
    topics: ["বীজগণিত - অধ্যায় ৩, ৪", "জ্যামিতি - অধ্যায় ৭", "পাটিগণিত - অধ্যায় ১, ২", "ত্রিকোণমিতি - অধ্যায় ৯"],
    importance: "অতি গুরুত্বপূর্ণ",
    createdAt: new Date().toISOString(),
  },
  {
    id: "s2",
    subjectId: "1",
    subjectName: "আল-কুরআন ও তাজবিদ",
    title: "বার্ষিক পরীক্ষার সাজেশন",
    description: "কুরআন তিলাওয়াত ও তাজবিদের গুরুত্বপূর্ণ বিষয়সমূহ।",
    examType: "বার্ষিক",
    topics: ["তাজবিদের মূলনীতি", "মাখরাজুল হুরুফ", "সূরা পরিচিতি", "ওয়াকফ ও ইবতিদা"],
    importance: "গুরুত্বপূর্ণ",
    createdAt: new Date().toISOString(),
  },
  {
    id: "s3",
    subjectId: "5",
    subjectName: "ইংরেজি",
    title: "Test Exam Suggestion",
    description: "Important topics for the upcoming test examination.",
    examType: "টেস্ট",
    topics: ["Grammar - Tense, Voice, Narration", "Paragraph Writing", "Letter Writing", "Reading Comprehension"],
    importance: "গুরুত্বপূর্ণ",
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "a1",
    title: "বার্ষিক পরীক্ষার সময়সূচী প্রকাশিত",
    content: "আগামী ১৫ ফেব্রুয়ারি থেকে বার্ষিক পরীক্ষা শুরু হবে। সকল ছাত্র-ছাত্রীকে নিজ নিজ রুটিন সংগ্রহ করতে অনুরোধ করা হচ্ছে।",
    type: "urgent",
    createdAt: new Date().toISOString(),
  },
  {
    id: "a2",
    title: "শিক্ষা সফর - জানুয়ারি ২৫",
    content: "আগামী ২৫ জানুয়ারি মাদরাসার পক্ষ থেকে শিক্ষা সফরের আয়োজন করা হয়েছে। যোগ দিতে ইচ্ছুক ছাত্ররা ক্লাস টিচারের সাথে যোগাযোগ করুন।",
    type: "info",
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: "m1",
    senderName: "শিক্ষক - মাওলানা আব্দুর রহমান",
    message: "আজকের কুরআনের ক্লাসে সবাই সূরা আল-মুলক তিলাওয়াত করবে। ভালোভাবে প্রস্তুতি নাও।",
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    isAdmin: true,
  },
  {
    id: "m2",
    senderName: "রাহিম",
    message: "স্যার, আজকের গণিতের হোমওয়ার্ক কি পাতা থেকে পাতা পর্যন্ত?",
    timestamp: new Date(Date.now() - 2400000).toISOString(),
    isAdmin: false,
  },
  {
    id: "m3",
    senderName: "করিম",
    message: "আজকে কি ইংরেজি ক্লাস হবে?",
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    isAdmin: false,
  },
];
